url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "SyFI Lab" # the name of your site, e.g. ACME Corp.
description: "Systems for Future Intelligence"
permalink: /blog/:year-:month-:day-:title/
